language: java
jdk:
  - oraclejdk8
before_install:
 - chmod +x gradlew
deploy:
  provider: heroku
  api_key: fb2289f8-3099-4ae3-a2da-8c1b79434dcc
  strategy: git
  app:
    master: wefactor-customer
    develop: evening-shelf-2330