INSERT INTO account (id,roles) values ('1','USER');
INSERT INTO userprofile (id, description, email, first_name, last_name, name, password, username, my_account, provider_id,image_url) VALUES ('1', 'Hallo ich bin ein Testuser', 'testuser@testmail.de', 'Max', 'Mustermann', 'Testuser','12345678', 'Testuser','1','WEFACTOR','http://www.localcrimenews.com/wp-content/uploads/2013/07/default-user-icon-profile.png');
INSERT INTO entry (id, changes, entry_type, teaser, language, entry_code_text, entry_date, entry_description, name, my_account, created_date, last_modified_date,created_by_id,last_modified_by_id,inactive) VALUES ('1','master','Master','This is an auto generated example of an entry in weFactor','java', 'public static void main', '2014-01-01', '<p>This is an auto generated example of an entry in weFactor</p>','Run a java application', '1','2014-01-01','2014-01-01','1','1','N');
INSERT INTO entry (id, changes, entry_type, teaser, language, entry_code_text, entry_date, entry_description, name, my_account, created_date, last_modified_date,created_by_id,last_modified_by_id,inactive,master_of_version) VALUES ('2','changed something', 'Version','This is a new version of an auto generated example of an entry in weFactor','java', 'public', '2014-01-01', '<p>This is a new version of an auto generated example of an entry in weFactor</p>','Run a java application', '1','2014-01-01','2014-01-01','1','1','N','1');
INSERT INTO entry (id, changes, entry_type, teaser, language, entry_code_text, entry_date, entry_description, name, my_account, created_date, last_modified_date,created_by_id,last_modified_by_id,inactive,master_of_version) VALUES ('3','changed something', 'Version','This is a new version of an auto generated example of an entry in weFactor','java', 'public', '2014-01-01', '<p>This is a new version of an auto generated example of an entry in weFactor</p>','Run a java application', '1','2014-01-01','2014-01-01','1','1','N','1');
INSERT INTO entry (id, changes, entry_type, teaser, language, entry_code_text, entry_date, entry_description, name, my_account, created_date, last_modified_date,created_by_id,last_modified_by_id,inactive,master_of_version) VALUES ('4','changed something', 'Version','This is a new version of an auto generated example of an entry in weFactor','java', 'public', '2014-01-01', '<p>This is a new version of an auto generated example of an entry in weFactor</p>','Run a java application', '1','2014-01-01','2014-01-01','1','1','N','1');
INSERT INTO entry (id, changes, entry_type, teaser, language, entry_code_text, entry_date, entry_description, name, my_account, created_date, last_modified_date,created_by_id,last_modified_by_id,inactive,master_of_version) VALUES ('5','changed something', 'Version','This is a new version of an auto generated example of an entry in weFactor','java', 'public', '2014-01-01', '<p>This is a new version of an auto generated example of an entry in weFactor</p>','Run a java application', '1','2014-01-01','2014-01-01','1','1','N','1');
INSERT INTO entry (id, changes, entry_type, teaser, language, entry_code_text, entry_date, entry_description, name, my_account, created_date, last_modified_date,created_by_id,last_modified_by_id,inactive,master_of_version) VALUES ('6','changed something', 'Version','This is a new version of an auto generated example of an entry in weFactor','java', 'public', '2014-01-01', '<p>This is a new version of an auto generated example of an entry in weFactor</p>','Run a java application', '1','2014-01-01','2014-01-01','1','1','N','1');
INSERT INTO entry (id, changes, entry_type, teaser, language, entry_code_text, entry_date, entry_description, name, my_account, created_date, last_modified_date,created_by_id,last_modified_by_id,inactive,master_of_version) VALUES ('7','changed something', 'Version','This is a new version of an auto generated example of an entry in weFactor','java', 'public', '2014-01-01', '<p>This is a new version of an auto generated example of an entry in weFactor</p>','Run a java application', '1','2014-01-01','2014-01-01','1','1','N','1');
INSERT INTO entry (id, changes, entry_type, teaser, language, entry_code_text, entry_date, entry_description, name, my_account, created_date, last_modified_date,created_by_id,last_modified_by_id,inactive,master_of_version) VALUES ('8','changed something', 'Version','This is a new version of an auto generated example of an entry in weFactor','java', 'public', '2014-01-01', '<p>This is a new version of an auto generated example of an entry in weFactor</p>','Run a java application', '1','2014-01-01','2014-01-01','1','1','N','1');
INSERT INTO entry (id, changes, entry_type, teaser, language, entry_code_text, entry_date, entry_description, name, my_account, created_date, last_modified_date,created_by_id,last_modified_by_id,inactive,master_of_version) VALUES ('9','changed something', 'Version','This is a new version of an auto generated example of an entry in weFactor','java', 'public', '2014-01-01', '<p>This is a new version of an auto generated example of an entry in weFactor</p>','Run a java application', '1','2014-01-01','2014-01-01','1','1','N','1');
INSERT INTO entry (id, changes, entry_type, teaser, language, entry_code_text, entry_date, entry_description, name, my_account, created_date, last_modified_date,created_by_id,last_modified_by_id,inactive,master_of_version) VALUES ('10','changed something', 'Version','This is a new version of an auto generated example of an entry in weFactor','java', 'public', '2014-01-01', '<p>This is a new version of an auto generated example of an entry in weFactor</p>','Run a java application', '1','2014-01-01','2014-01-01','1','1','N','1');
INSERT INTO entry (id, changes, entry_type, teaser, language, entry_code_text, entry_date, entry_description, name, my_account, created_date, last_modified_date,created_by_id,last_modified_by_id,inactive,master_of_version) VALUES ('11','changed something', 'Version','This is an auto generated example of an entry in weFactor','java', 'public static void main', '2014-01-01', '<p>This is an auto generated example of an entry in weFactor</p>','Run a java application', '1','2014-01-01','2014-01-01','1','1','N','1');
INSERT INTO entry (id, changes, status, entry_type, teaser, language, entry_code_text, entry_date, entry_description, name, my_account, created_date, last_modified_date,created_by_id,last_modified_by_id,inactive,master_of_proposal) VALUES ('12','changed something','NEW', 'Proposal','This is an auto generated example of an entry in weFactor','java', 'public static void main', '2014-01-01', '<p>This is an auto generated example of an entry in weFactor</p>','Run a java application', '1','2014-01-01','2014-01-01','1','1','N','1');
INSERT INTO entry (id, changes, status, entry_type, teaser, language, entry_code_text, entry_date, entry_description, name, my_account, created_date, last_modified_date,created_by_id,last_modified_by_id,inactive,master_of_proposal) VALUES ('13','changed something','ACCEPTED', 'Proposal','This is an auto generated example of an entry in weFactor','java', 'public static void main', '2014-01-01', '<p>This is an auto generated example of an entry in weFactor</p>','Run a java application', '1','2014-01-01','2014-01-01','1','1','N','1');
INSERT INTO entry (id, changes, status, entry_type, teaser, language, entry_code_text, entry_date, entry_description, name, my_account, created_date, last_modified_date,created_by_id,last_modified_by_id,inactive,master_of_proposal) VALUES ('14','changed something','REJECTED', 'Proposal','This is an auto generated example of an entry in weFactor','java', 'public static void main', '2014-01-01', '<p>This is an auto generated example of an entry in weFactor</p>','Run a java application', '1','2014-01-01','2014-01-01','1','1','N','1');

INSERT INTO timeline_event (id, event_type, source, target, event_date, oid_identification, oid_type, oid_name, created_date, last_modified_date,created_by_id,last_modified_by_id) values ('1','MADE_PROPOSAL', '1', '1','2014-01-01','1','Entry','Test','2014-01-01','2014-01-01','1','1');

