INSERT INTO account (id,roles) values ('1','USER');
INSERT INTO userprofile (id, description, email, first_name, last_name, name, password, username, my_account, provider_id,image_url) VALUES ('1', 'Hallo ich bin ein Testuser', 'testuser@testmail.de', 'Max', 'Musermann', 'Testuser','12345678', 'Testuser','1','WEFACTOR','http://www.localcrimenews.com/wp-content/uploads/2013/07/default-user-icon-profile.png');
INSERT INTO Entry (id, Entry_type, teaser, language, Entry_code_text, Entry_date, Entry_description, name, my_account, created_date, last_modified_date,created_by_id,last_modified_by_id,inactive) VALUES ('1','Master','This is an auto generated example of an Entry in weFactor','java', 'public static void main', '2014-01-01', '<p>This is an auto generated example of an Entry in weFactor</p>','Run a java application', '1','2014-01-01','2014-01-01','1','1','N');
INSERT INTO Entry (id, Entry_type, teaser, language, Entry_code_text, Entry_date, Entry_description, name, my_account, created_date, last_modified_date,created_by_id,last_modified_by_id,inactive,master_Entry) VALUES ('2','Version','This is a new version of an auto generated example of an Entry in weFactor','java', 'public', '2014-01-01', '<p>This is a new version of an auto generated example of an Entry in weFactor</p>','Run a java application', '1','2014-01-01','2014-01-01','1','1','N','1');
INSERT INTO Entry (id, Entry_type, teaser, language, Entry_code_text, Entry_date, Entry_description, name, my_account, created_date, last_modified_date,created_by_id,last_modified_by_id,inactive,master_Entry) VALUES ('3','Version','This is a new version of an auto generated example of an Entry in weFactor','java', 'public', '2014-01-01', '<p>This is a new version of an auto generated example of an Entry in weFactor</p>','Run a java application', '1','2014-01-01','2014-01-01','1','1','N','1');
INSERT INTO Entry (id, Entry_type, teaser, language, Entry_code_text, Entry_date, Entry_description, name, my_account, created_date, last_modified_date,created_by_id,last_modified_by_id,inactive,master_Entry) VALUES ('4','Version','This is a new version of an auto generated example of an Entry in weFactor','java', 'public', '2014-01-01', '<p>This is a new version of an auto generated example of an Entry in weFactor</p>','Run a java application', '1','2014-01-01','2014-01-01','1','1','N','1');
INSERT INTO Entry (id, Entry_type, teaser, language, Entry_code_text, Entry_date, Entry_description, name, my_account, created_date, last_modified_date,created_by_id,last_modified_by_id,inactive,master_Entry) VALUES ('5','Version','This is a new version of an auto generated example of an Entry in weFactor','java', 'public', '2014-01-01', '<p>This is a new version of an auto generated example of an Entry in weFactor</p>','Run a java application', '1','2014-01-01','2014-01-01','1','1','N','1');
INSERT INTO Entry (id, Entry_type, teaser, language, Entry_code_text, Entry_date, Entry_description, name, my_account, created_date, last_modified_date,created_by_id,last_modified_by_id,inactive,master_Entry) VALUES ('6','Version','This is a new version of an auto generated example of an Entry in weFactor','java', 'public', '2014-01-01', '<p>This is a new version of an auto generated example of an Entry in weFactor</p>','Run a java application', '1','2014-01-01','2014-01-01','1','1','N','1');
INSERT INTO Entry (id, Entry_type, teaser, language, Entry_code_text, Entry_date, Entry_description, name, my_account, created_date, last_modified_date,created_by_id,last_modified_by_id,inactive,master_Entry) VALUES ('7','Version','This is a new version of an auto generated example of an Entry in weFactor','java', 'public', '2014-01-01', '<p>This is a new version of an auto generated example of an Entry in weFactor</p>','Run a java application', '1','2014-01-01','2014-01-01','1','1','N','1');
INSERT INTO Entry (id, Entry_type, teaser, language, Entry_code_text, Entry_date, Entry_description, name, my_account, created_date, last_modified_date,created_by_id,last_modified_by_id,inactive,master_Entry) VALUES ('8','Version','This is a new version of an auto generated example of an Entry in weFactor','java', 'public', '2014-01-01', '<p>This is a new version of an auto generated example of an Entry in weFactor</p>','Run a java application', '1','2014-01-01','2014-01-01','1','1','N','1');
INSERT INTO Entry (id, Entry_type, teaser, language, Entry_code_text, Entry_date, Entry_description, name, my_account, created_date, last_modified_date,created_by_id,last_modified_by_id,inactive,master_Entry) VALUES ('9','Version','This is a new version of an auto generated example of an Entry in weFactor','java', 'public', '2014-01-01', '<p>This is a new version of an auto generated example of an Entry in weFactor</p>','Run a java application', '1','2014-01-01','2014-01-01','1','1','N','1');
INSERT INTO Entry (id, Entry_type, teaser, language, Entry_code_text, Entry_date, Entry_description, name, my_account, created_date, last_modified_date,created_by_id,last_modified_by_id,inactive,master_Entry) VALUES ('10','Version','This is a new version of an auto generated example of an Entry in weFactor','java', 'public', '2014-01-01', '<p>This is a new version of an auto generated example of an Entry in weFactor</p>','Run a java application', '1','2014-01-01','2014-01-01','1','1','N','1');
INSERT INTO Entry (id, Entry_type, teaser, language, Entry_code_text, Entry_date, Entry_description, name, my_account, created_date, last_modified_date,created_by_id,last_modified_by_id,inactive,master_Entry) VALUES ('11','Version','This is an auto generated example of an Entry in weFactor','java', 'public static void main', '2014-01-01', '<p>This is an auto generated example of an Entry in weFactor</p>','Run a java application', '1','2014-01-01','2014-01-01','1','1','N','1');
INSERT INTO Entry (id, Entry_type, teaser, language, Entry_code_text, Entry_date, Entry_description, name, my_account, created_date, last_modified_date,created_by_id,last_modified_by_id,inactive,master_Entry) VALUES ('12','Proposal','This is an auto generated example of an Entry in weFactor','java', 'public static void main', '2014-01-01', '<p>This is an auto generated example of an Entry in weFactor</p>','Run a java application', '1','2014-01-01','2014-01-01','1','1','N','1');

INSERT INTO timeline_event (id, event_type, source, target, event_date, oid_identification, oid_type, oid_name, created_date, last_modified_date,created_by_id,last_modified_by_id) values ('1','MADE_PROPOSAL', '1', '1','2014-01-01','1','Entry','Test','2014-01-01','2014-01-01','1','1');

